#cloud-config
# Cloud config for Elasticsearch nodes 

runcmd:
  # Install docker
  - curl -sSL https://get.docker.com/ | sudo sh
  # Download Docker image
  - sudo docker pull elasticsearch
  # Run Docker images
  - sudo docker run -p 9200:9200 -d elasticsearch
