#cloud-config 

packages:
  - nginx

write_files:
  - path: /etc/nginx/nginx.conf
    content: |
write_files:
  - path: /etc/nginx/nginx.conf
    content: |
      events {
      worker_connections  1024;
      }

      http {

        server {

          listen       8080;

          error_log   elasticsearch-errors.log;
          access_log  elasticsearch.log;

          location / {

            if ($request_filename ~ "_cluster") {
              return 403;
              break;
            }

            proxy_pass http://localhost:9200;
            proxy_redirect off;

            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  Host $http_host;

            auth_basic           "ElasticSearch";
            auth_basic_user_file passwords;

            rewrite ^(.*)$ $1 break;
            rewrite_log on;

            return 403;

          }
        }
      }
  - path: /etc/nginx/passwords
    content: | 
      test:$apr1$ClN2xdA3$AtJ0Yifq0Y.sGF42GDmUv1
      
runcmd:
  # Install docker
  - curl -sSL https://get.docker.com/ | sudo sh
  # Download Docker image
  - sudo docker pull elasticsearch
  # Run Docker images
  - sudo docker run -p 9200:9200 -d elasticsearch -Dcluster.name="artirix"
