#cloud-config 

packages:
  - nginx
  - openjdk-7-jre

write_files:
  - path: /etc/nginx/nginx.conf
    content: |
write_files:
  - path: /etc/nginx/nginx.conf
    content: |
      events {
      worker_connections  1024;
      }

      http {

        server {

          listen       8080;

          error_log   elasticsearch-errors.log;
          access_log  elasticsearch.log;

          location / {

            if ($request_filename ~ "_cluster") {
              return 403;
              break;
            }

            proxy_pass http://localhost:9200;
            proxy_redirect off;

            proxy_set_header  X-Real-IP  $remote_addr;
            proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header  Host $http_host;

            auth_basic           "ElasticSearch";
            auth_basic_user_file passwords;

            rewrite ^(.*)$ $1 break;
            rewrite_log on;

            return 403;

          }
        }
      }
  - path: /etc/nginx/passwords
    content: | 
      test:$apr1$ClN2xdA3$AtJ0Yifq0Y.sGF42GDmUv1
  - path: /etc/cloud-init.sh
    content: |
      #!/bin/bash
      wget https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.3.5/elasticsearch-2.3.5.deb -P /tmp/ 
      dpkg -i /tmp/elasticsearch-2.3.5.deb 
      update-rc.d elasticsearch defaults
      /usr/share/elasticsearch/bin/plugin install cloud-aws -b
      echo 'cloud.aws.access_key: AKIAIX5ODQQLTEZEGCAA' | tee --append /etc/elasticsearch/elasticsearch.yml
      echo 'cloud.aws.secret_key: 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' | tee --append /etc/elasticsearch/elasticsearch.yml 
      echo 'cluster.name: artirix' | tee --append /etc/elasticsearch/elasticsearch.yml 
      echo 'http.port: 9200' | tee --append /etc/elasticsearch/elasticsearch.yml
      echo 'cloud.aws.protocol: http' | tee --append /etc/elasticsearch/elasticsearch.yml
      echo 'cloud.aws.region: eu-west-1' | tee --append /etc/elasticsearch/elasticsearch.yml
      echo 'discovery.type: ec2' | tee --append /etc/elasticsearch/elasticsearch.yml
      echo 'network.host: [ "_site_", "_local_" ]' | tee --append /etc/elasticsearch/elasticsearch.yml
      service elasticsearch start    
      
runcmd:
  # Install ElasticSearch  
  - chmod +x /etc/cloud-init.sh
  - sh /etc/cloud-init.sh
